/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionpedidos;


import gestionpedidos.LineaPedido;
import gestionpedidos.Producto;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author javier
 */
public class MiVentana extends javax.swing.JFrame {
            private DefaultListModel dlm_productos;
            private DefaultListModel dlm_pedidos;
            private DefaultListModel dlm_filtrados;
            private ArrayList<Pedido> listaPedidos;
            private Pedido pedido;
    /**
     * Creates new form MiVentana
     */
    public MiVentana() {
        initComponents();
        listaPedidos = new ArrayList();
        dlm_pedidos = new DefaultListModel();
        dlm_productos = new DefaultListModel();
        dlm_filtrados = new DefaultListModel();
        lst_productos.setModel(dlm_productos);
        lst_pedidos.setModel(dlm_pedidos);
        lst_filtrados.setModel(dlm_filtrados);
        lst_productos.updateUI();
        
        leerProductos("productos.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_productos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_añadir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nomCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_total = new javax.swing.JButton();
        btn_iniciar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_pedidos = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        txt_filtrados = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_filtrados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Productos Disponibles:");

        lst_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElegirCantidad(evt);
            }
        });
        jScrollPane1.setViewportView(lst_productos);

        jLabel3.setText("Cantidad:");

        btn_añadir.setText("Añadir a la Cesta");
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Cliente");

        jLabel5.setText("Total del pedido:");

        btn_total.setText("Finalizar Pedido");
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        btn_iniciar.setText("Iniciar pedido");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        jLabel6.setText("Pedidos Realizados:");

        jScrollPane2.setViewportView(lst_pedidos);

        jLabel7.setText("Filtrar por categoría:");

        btn_buscar.setText("Filtrar por categoría");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lst_filtrados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lst_filtrados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_iniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(txt_nomCliente, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_añadir, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txt_cantidad)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(txt_filtrados, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_total)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_total, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(472, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6))
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(txt_nomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btn_iniciar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_añadir)
                                    .addComponent(btn_total)))
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_filtrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElegirCantidad(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElegirCantidad
       int i = lst_productos.getSelectedIndex();
       Producto p = (Producto) dlm_productos.getElementAt(i);
       
        for (int j = 0; j < dlm_productos.getSize(); j++) {
            
            
        }
    }//GEN-LAST:event_ElegirCantidad

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
          int i = lst_productos.getSelectedIndex();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Error: Primero debe seleccionar un producto");
            return;
        }

        if (txt_cantidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Debe introducir una cantidad");
            txt_cantidad.requestFocus();
            return;
        }

        Producto p = (Producto) dlm_productos.getElementAt(i);
        int cantidad = Integer.parseInt(txt_cantidad.getText().trim());
        
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "Error: La cantidad debe ser mayor que cero");
            return;
        }

        if (cantidad > p.getStock()) {
            JOptionPane.showMessageDialog(this,  "Error: Stock insuficiente. Disponible: " + p.getStock());
            return;
        }

        int nStock = p.getStock() - cantidad;
        p.setStock(nStock);

        LineaPedido lp = new LineaPedido(p, cantidad);
        pedido.addlineaPedido(lp);

        if (nStock <= 0) {
            dlm_productos.removeElementAt(i); // Eliminar por índice
        }

        // 9. Actualizar interfaz
        lst_productos.repaint();
        txt_cantidad.setText(""); // Limpiar solo el campo de cantidad
        
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
         String nombre = txt_nomCliente.getText();
         if(nombre.isBlank()){
            JOptionPane.showMessageDialog(this, "Error: \n Debe poner su nombre de cliente");
        }
         else{
             JOptionPane.showMessageDialog(this, "¡Se ha iniciado su pedido!" + " Bienvenido " + nombre);
         }
        pedido = new Pedido(nombre);
        
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        // TODO add your handling code here:
        if(pedido == null){
            JOptionPane.showMessageDialog(this, "\n El producto está vacio por lo que es precio es de 0" + "€");
        }
        else{
             calcularTotalPedido(pedido);
            listaPedidos.add(pedido);
            dlm_pedidos.addElement("\n" + pedido);
        }
       
        
        
    }//GEN-LAST:event_btn_totalActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String f = txt_filtrados.getText();
        boolean encontrado = false;
        
        if(f.isBlank()){
            JOptionPane.showMessageDialog(this, "Ingrese una categoría para filtrar");
        }
        dlm_filtrados.clear();
        
        for (int j = 0; j < dlm_productos.getSize(); j++) {
            Producto p = (Producto) dlm_productos.getElementAt(j);
            if(p.getCategoria().equalsIgnoreCase(f)){
                dlm_filtrados.addElement(p);
                encontrado = true;
            }
        }
        if(!encontrado){
            JOptionPane.showMessageDialog(this, "\n No hay ninguna coincidencia \n");  
        }
    }//GEN-LAST:event_btn_buscarActionPerformed
    
    public void calcularTotalPedido(Pedido p){
           // 1. Calcular el total (parte original)
    ArrayList listaProductos = p.getLineasPedido();
    double subtotal = 0.0, total = 0.0;
    
    for (int i = 0; i < listaProductos.size(); i++) {
        LineaPedido lp = (LineaPedido) listaProductos.get(i);
        Producto prod = (Producto) lp.getProducto();
        int c = lp.getCantidad();
        subtotal = prod.getPrecio() * c;
        total = total + subtotal;
    }
    
    p.setTotal(total);
    txt_total.setText(String.valueOf(total));
    
    // 2. Guardar en archivo (nueva funcionalidad integrada)
    try {
        FileWriter fw = new FileWriter("pedidos.txt", true); // true para append (añadir sin borrar)
        BufferedWriter bw = new BufferedWriter(fw);
        
        bw.write("--- NUEVO PEDIDO ---");
        bw.newLine();
        bw.write("Cliente: " + p.getCliente());
        bw.newLine();
        bw.write("Total: " + total + "€");
        bw.newLine();
        bw.write("Productos:");
        bw.newLine();
        
        for (LineaPedido linea : p.getLineasPedido()) {
            Producto prod = linea.getProducto();
            bw.write("- " + prod.getNombre() + 
                    " | Cantidad: " + linea.getCantidad() + 
                    " | Precio: " + prod.getPrecio() + "€");
            bw.newLine();
        }
        
        bw.write("----------------------------");
        bw.newLine();
        bw.close();
        
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el pedido: " + ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiVentana().setVisible(true);
            }
        });
    }
    
    public void leerProductos(String FicheroP){
        try {
            FileReader fr = new FileReader(FicheroP);
            BufferedReader bfr = new BufferedReader(fr);
            String linea;
            String nombre;
            String categoria;
            double precio;
            int stock;
            
            try {
                while((linea = bfr.readLine()) != null){
                        String trozos[] = linea.split(";");
                        nombre = trozos[0];
                        categoria = trozos[1];
                        precio = Double.parseDouble(trozos[2]);
                        stock = Integer.parseInt(trozos[3]);
                        if(stock > 0){
                             Producto p = new Producto(nombre, categoria, precio, stock);
                             dlm_productos.addElement(p);
                        }
                    }      
            } catch (IOException ex) {
                Logger.getLogger(MiVentana.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MiVentana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_filtrados;
    private javax.swing.JList<String> lst_pedidos;
    private javax.swing.JList<String> lst_productos;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_filtrados;
    private javax.swing.JTextField txt_nomCliente;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
